# source: .

exclude:
  - NO_GIT
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - bower.json
  - bower_components
  - gulpfile.js

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false
  toc_levels: 2..4
  # Remove typographic single quotes (but allow typographic double quotes)
  smart_quotes: [ 'apos', 'apos', 'ldquo', 'rdquo' ]
  # This is needed to disable builtin highlight-rouge
  syntax_highlighter: true
  enable_coderay: false

gems:
  - jekyll-compass
  - breakpoint

permalink: pretty

defaults:
  -
    scope:
      path: ''
    values:
      layout: layout
